version: '3'
services:
  app:
    container_name: dmgct-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../var/html:/var/www/html
    networks:
      dmgct_network:
        ipv4_address: 172.23.0.10
networks:
  dmgct_network:
    external: true
